name: Test & Build

on:
  push:
  pull_request:

jobs:
  test:
    name: Test SynackAPI Package
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Initialize Python 3.10
        uses: actions/setup-python@v1
        with:
          python-version: "3.10"
      - name: Install Dependencies
        run: python -m pip install -r ./requirements.txt
      - name: Lint SynackAPI with Flake8
        uses: py-actions/flake8@v2
        with:
          path: "src"
      - name: Run Unit Tests
        run: python -m unittest discover -s test
  build:
    name: Build SynackAPI Package
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Initialize Python 3.10
        uses: actions/setup-python@v1
        with:
          python-version: "3.10"
      - name: Build binary wheel and a source tarball
        run: python setup.py sdist
      - name: Upload Build
        uses: actions/upload-artifact@v2
        with:
          name: dist
          path: dist/
          retention-days: 1
